### ISSUE TITLE
Cannot find module require-dir

### ISSUE THREAD

**Issue by aligneddev** [PWKad/au-ps-comparison#2]
I'm on Windows 7 and am newer to Gulp. I tried running the command prompt under administrator, but that didn't help either.

 I ran the npm installs and when I rung gulp watch, I keep getting Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users{}\Source\Repos\au-ps-comparison\
gulpfile.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Any ideas on how to get this working?

Thanks!

**Comment by aligneddev** [comment]
I had to run npm install. I'll make a pull request for your readme.

**Comment by aligneddev** [comment]
Actually, I just missed the npm install step that is already in your readme :-).
